version: "3"

volumes:
  db-data: {}

services:
  php-apache:
    build: ./php
    container_name: my-php-apache
    volumes:
      - ./htdocs:/var/www/html
    restart: always
    ports:
      - 80:80
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    container_name: my-mysql
    volumes:
      - db-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - "TZ=Asia/Tokyo"
    restart: always

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: my-phpmyadmin
    environment:
      - PMA_HOST=mysql
    restart: always
    ports:
      - 8080:80
    depends_on:
      - mysql
